### ISSUE TITLE
Remove sa_cookie from events

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#101]
[@MatiasKlemola](https://twitter.com/MatiasKlemola)

**Comment by khrome83** [comment]
I was about to add event tracking to my site.

https://github.com/khrome83/khrome.dev/issues/13

But I am going to wait for the cookie part to be removed. My use case - check when some links are clicked.

**Comment by adriaanvanrossum** [comment]
This is now possible @khrome83!

- https://sa.khrome.dev/latest.js
- https://scripts.simpleanalyticscdn.com/latest.js

**Comment by khrome83** [comment]
@adriaanvanrossum - awesome. Looking at setting it up now.

**Comment by khrome83** [comment]
Created a visual bug I will fix tomorrow. 🤷‍♂But it's integrated!

Clicking "AddToAny" link, submitting a form, will now be tracked.

Very easy to set up, thank you @adriaanvanrossum.

It's great to pay for a product, you can see first hand how it changes overnight. And to see feedback be taken into account.

**Comment by adriaanvanrossum** [comment]
We love feedback and that's what drives our new features. So thanks for that. Happy it works for you. Closing it now.

**Comment by khrome83** [comment]
@adriaanvanrossum - is there a delay before events show in the dashboard? I am seeing them register, so awesome!

**Comment by adriaanvanrossum** [comment]
There is a delay of maximum a few minutes. I will check now to see if it works within that time span.

**Comment by adriaanvanrossum** [comment]
I just tested it and it's was registered within a few minutes:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/72664464-81c6fe80-39fe-11ea-9fa5-7bca78dc4b61.jpg"></kbd>

**Comment by khrome83** [comment]
All good!
