### ISSUE TITLE
Apply all cache and speed tips

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#104]
From http://webpagetest.org/performance_optimization.php?test=190415_9H_0825e8b2575fd1cac975a636993c6b1b&run=3#cache_static_content

**Comment by daniellockyer** [comment]
Let's make it fast!

**Comment by daniellockyer** [comment]
Just went through and fixed any ones we missed the other day. We should be good to close this for now :+1:

![2019-11-22-09:46:48](https://user-images.githubusercontent.com/964245/69393907-09e59c00-0d0d-11ea-9b4c-8b700a7295fe.png)

**Comment by adriaanvanrossum** [comment]
Awesome, thanks @daniellockyer!
