### ISSUE TITLE
Sort the overview of sites based on activity

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#107]
Sort the overview of sites (on the dashboard) based on activity (via support tg)

Related to https://github.com/simpleanalytics/roadmap/issues/84

**Comment by hellodeibu** [comment]
@adriaanvanrossum would this one be the same idea as #271, or is this for a different kind of sorting option altogether?

**Comment by adriaanvanrossum** [comment]
I think this is the same. So we can close this as you already implemented this! Woop woop!
