### ISSUE TITLE
Convert the last metric column into "tabs" to allow additional metrics

### ISSUE THREAD

**Issue by amritnagi** [simpleanalytics/roadmap#169]
UX Suggestion - convert the last column into a "tabs" so you can switch between the different metrics.

1) This would help make the page look cleaner
2) Make it easier to add additional metrics

Simple mockup using 3, but could easily do 4, and retain countries as a column
![image](https://user-images.githubusercontent.com/25029371/69338669-99327700-0c5b-11ea-8656-aeb089aa5476.png)

**Comment by adriaanvanrossum** [comment]
I think we solved this with the drop down at the moment:

<kbd><img width="560" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96729085-10fdaa00-13b5-11eb-898c-b8c9982ce217.png"></kbd>

We could also add OS's to a drop down we show in Browsers.
