### ISSUE TITLE
Fix padding issue with shortcuts in date picker

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#170]
<kbd><img width="320px" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/69477495-81085680-0e19-11ea-8fd1-53f5bcbc729a.jpeg"></kbd>

cc @Amritnagi

**Comment by adriaanvanrossum** [comment]
Fixed, will deploy to production later today.

**Comment by james-k-fox** [comment]
I was going to suggest some CSS to fix pre-fixed date shortcuts but I see you have reported already resolving this. My suggestion was:
`.shortcut-buttons-flatpickr-button {     
    font-size: 12px;
    line-height: 20px;
    height: 20px;
    padding: 0 6px;
    margin: 7px 3px;
}`

**Comment by adriaanvanrossum** [comment]
Thanks @james-k-fox 🙏 It's more or less the same what we did 🥳

We also moved the shortcuts to the top of the date picker. It's all deployed now.

<kbd><img width="800" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/69599780-e38f6b80-1040-11ea-82e7-00337d2347c7.jpg"></kbd>

**Comment by james-k-fox** [comment]
Awesome! Thanks for the update :-)
