### ISSUE TITLE
Legal compliance

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#174]
It's important to have everything 100% correct legal wise. We got great advise from @legalmonster and wandapeters.

### The tasks we need to do

- [x] Add cookie policy link at signup
- [x] Add terms of service link at signup
- [x] Ask permission for marketing purposes at the demo email input
- [x] Anonymize user agent before it gets stored
- [x] Update privacy policy
- [x] Update terms of service

**Comment by wandapeters** [comment]
joehoe!
Kan je mijn prive email gebruiken? wandapeters@gmail.com
spanks!

*Wanda Peters*
Head of Operations

wanda@membergetmember.co | 06 2549 7394


*Member Get Member Company*Oostelijke Handelskade 865 | 1019 BW Amsterdam
www.membergetmember.co


Op di 26 nov. 2019 om 10:27 schreef Adriaan <notifications@github.com>:

**Comment by adriaanvanrossum** [comment]
All done!
