### ISSUE TITLE
Check why tweets do not show

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#183]
<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/70309907-da578900-180e-11ea-91ad-54df793b5f97.jpeg"></kbd>

**Comment by amritnagi** [comment]
Remember we saw this on my stats too... it was working if you entered a wider range of dates.

I think it only seems to work if you do +/- 1 day to the date.

e.g
https://simpleanalytics.com/tailwindtoolbox.com/referrers/twitter?start=2019-12-07&end=2019-12-09

**Comment by adriaanvanrossum** [comment]
[Another customer](https://secure.helpscout.net/thread/1085742146/3077602240/orig-popup/) with multiple days selected:

![Image](https://user-images.githubusercontent.com/1079135/74726124-38591180-523f-11ea-9760-e77fcc23e835.png)

**Comment by adriaanvanrossum** [comment]
Fixed:

![CleanShot 2020-04-08 at 23 22 19@2x](https://user-images.githubusercontent.com/1079135/78835395-66adce80-79f0-11ea-9794-e8db6d7ddbd0.jpg)
