### ISSUE TITLE
Bug: Clicking an Individual Top Page Does Not Maintain Date Filtering

### ISSUE THREAD

**Issue by calendee** [simpleanalytics/roadmap#189]
Expected : When I am looking at my site stats and have a date filter in place, I should be able to click one of the top pages and see that page with the same date filters applied.

Actual: Clicking a lit always applies the default date filter instead of the previously selected filter.

https://www.loom.com/share/d75005cf37f048609aa23768b90c609f

**Comment by jibsaramnim** [comment]
@calendee I stumbled upon this older issue, I think this has been long solved but I wanted to check with you to make sure I understand it right. If how it's working on Simple Analytics these days is not what you meant, could you re-open the issue and elaborate a bit more? If not, thanks so much for reporting, and apologies for not pinging you on this issue earlier!

**Comment by calendee** [comment]
@jibsaramnim  thanks for ggetting back to me. Yes, the issue seems resolved.
