### ISSUE TITLE
Firefox as Netscape

### ISSUE THREAD

**Issue by Macro-Jackson** [simpleanalytics/roadmap#195]
Mozilla Firefox visitors get a Netscape icon. Seems wrong.
Not even sure why the Netscape icon still exists. Is there still a Netscape browser?

**Comment by adriaanvanrossum** [comment]
The Netscape icon is an Easter Egg for browsers that we don't recognize. It should not show for Firefox. Could you share your website with us so we can check what is going on?

**Comment by Macro-Jackson** [comment]
See here: https://simpleanalytics.com/comphare.nl?start=2020-01-02&end=2020-01-02

**Comment by adriaanvanrossum** [comment]
Thank you! It seems like it couldn't detect what browser it was (https://simpleanalytics.com/comphare.nl.json?start=2020-01-02&end=2020-01-02):

```js
{
  ...
  "__agents": "INFO: Agents are aggregated on daily basis in UTC time and without any path. They can be slightly off depending on your time zone and path.",
  "agents": [
    ...,
    {
      "count": 11,
      "browser_name": "Mozilla",
      "browser_version": "5",
      "os_name": null,
      "os_version": null,
      "type": null
    },
    ...
  ],
  ...
}
```

We do see a new bot around that time. Did you use 2gdpr.com by any chance? We will add that one to the block list of robots. It's not showing any browser details, just this: `Mozilla/5.0 (compatible; 2GDPR/1.2; https://2gdpr.com)` We just deployed a fix that will block 2gdpr.com visits in the future.

**Comment by Macro-Jackson** [comment]
Yes, I've checked if my website with SA is now GDPR compliant and cookie free. :-)

**Comment by adriaanvanrossum** [comment]
Thanks for confirming and reporting! This makes our tool better for everybody. Really appreciate your help.
