### ISSUE TITLE
Browsers more/less button

### ISSUE THREAD

**Issue by Macro-Jackson** [simpleanalytics/roadmap#196]
In the domain overview you see the selection of browsers. There you'll see a more button. But this does only change to less when clicked. Even though there are more browsers that viewed the site.

**Comment by adriaanvanrossum** [comment]
Does this also happen for you when you go to https://simpleanalytics.com/simpleanalytics.com?

**Comment by Macro-Jackson** [comment]
Nope. But see here for yourself. https://simpleanalytics.com/comphare.nl
Weird thing is that when you view only today then it works. At least no more/less button anymore.

**Comment by adriaanvanrossum** [comment]
So the issue covers two bugs:

- [ ] It does not show all browsers that you see with the [Stats API](https://simpleanalytics.com/comphare.nl.json)
- [ ] The show more button should only show with more than 4 browsers

Thanks for reporting! Will fix.

**Comment by adriaanvanrossum** [comment]
@Macro-Jackson: @hellodeibu created a fix for this issue.

This resulted in a question for you. The numbers of the other browsers are so low that it's only shows 1 browser in the UI (we round them up to 1 percent). The [Stats API](https://simpleanalytics.com/comphare.nl.json) shows more, but with very low numbers. If we would show those browsers the dashboard would look like this:

<kbd><img width="260" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/71721094-2f91b500-2e24-11ea-8918-18165f9dce0d.png"></kbd>

This would clutter the UI in my opinion but maybe you have a nice thought on this. What would you expect to see in the UI?

**Comment by Macro-Jackson** [comment]
I fully agree with that it would clutter the interface. But I want to have the option to see them. So I'd suggest following option:
Show up to 4? by default (limited by 1% percentage)
With "More..." button show up to 10? (limited by 1% percentage)
And additionally a "Show all..." button to show all <1%. That button will need some coding because it must be depending on if there is a "More..."button in the first place and if there are browsers <1%.

But this is more a general issue. Same for countries and pages and I guess referrals will also have this issue.

You can even make this a setting which is default off to keep it simple for the people who like simple and when "Show all value" button setting is set to ON that this feature will be displayed.

**Comment by adriaanvanrossum** [comment]
Thanks @Macro-Jackson, we will continue with developing it based on your comments.

**Comment by hellodeibu** [comment]
Hello @Macro-Jackson! I'm happy to say that we've pushed an update that both fixes the bug you discovered and hopefully makes the agents list a bit more useful in situations like the one you experienced. Now when there are one or two very dominant browsers in your data, we decrease the level of rounding off somewhat to give you a more detailed view of the other browsers also being used. This way you we keep the dashboard readable while at the same time offering more detail when needed. 

What do you think? Does this make your experience better? Please let me know, I would love to hear your thoughts. And thank you so much for bringing this to our attention!

-Dave

**Comment by Macro-Jackson** [comment]
I think this is much better! Thanks.
