### ISSUE TITLE
Allow graph embed using custom domain

### ISSUE THREAD

**Issue by LeCodeCo** [simpleanalytics/roadmap#199]
One feature I'd like to see if the ability to embed custom graphs using a script available on something.example.com rather than from the Simple Analytics CDN's regular domain. This is because uBlock Origin seems to block the script when on the normal domain.

The embed script I'm referring to is this one: https://docs.simpleanalytics.com/embed-graph-on-your-site

**Comment by adriaanvanrossum** [comment]
That would be cool! I will add this to the other issues where we change our scripts. Thank you!

**Comment by adriaanvanrossum** [comment]
Done! https://growth.dashflo.net/embed.js

Let me know if this works for you
