### ISSUE TITLE
Send more data via the image.gif through URL parameters

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#209]
One of our customers asked for a feature request and I think it's great:

> You provide the alternative tracking code `<img src="https://api.simpleanalytics.io/hello.gif" alt="">` in the "noscript" tag, which is great. Obviously, this will be used for users who have JavaScript disabled. And it could even be used for companies that are handling extremely sensitive data and don't want to allow third-party JavaScript. Browsers and countries can be collected via the image-based solution as well.
> 
> But today, it's more and more common to restrict how the referrer header is sent (to other origins, at least). One example of such a restriction is the HTML tag `<meta name="referrer" content="origin">` that may be used in the "head" section of a document.
> 
> How does your image-based (1x1 GIF) tracking code work with such restrictions? I imagine the referrer header is the only way you can associate the recorded data with the correct account or site, right? If the referrer header is not sent (or trimmed), tracking does not work.
> 
> Couldn't you allow for the visited URL to be specified *explicitly*, instead of just accepting it *implicitly* from the referrer header?
> 
> `<img src="https://api.simpleanalytics.io/hello.gif?url=https://www.example.com/visited/page?supplied=params" alt="">`
> 
> The explicit value could even be used as a fallback only, i.e. when the implicit value is not available. Google Analytics includes the account's or site's unique tracking ID in the code as well, which simplifies associating visits with sites.

Let's put this on our roadmap and combine it when we work on our API. It's a nice Friday afternoon project.

**Comment by jakejarvis** [comment]
This would be great, since the GIF is the best way I could figure out how to collect stats from my AMP pages! (They're _very_ picky about scripts.)

https://amp.dev/documentation/components/amp-pixel/

**Comment by adriaanvanrossum** [comment]
Ah cool, this makes the use of it more clear.

**Comment by adriaanvanrossum** [comment]
This is now implemented!

See our documentation: https://docs.simpleanalytics.com/without-javascript
