### ISSUE TITLE
Referral link ssl error

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#214]
Referral link not accessible, ssl certificate expired 2 days ago

<img width="602" alt="Screenshot 2020-01-18 at 23 08 47" src="https://user-images.githubusercontent.com/5655500/72671256-ce82f780-3a47-11ea-856e-6f4fb1a0258c.png">

**Comment by adriaanvanrossum** [comment]
Thank you! We now fixed this.

**Comment by adriaanvanrossum** [comment]
We will also add it to our monitoring now ;)

**Comment by adriaanvanrossum** [comment]
Added to monitoring now.
