### ISSUE TITLE
Card gets associated with wrong country

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#215]
I changed my credit card, but the new card gets wrongly identified as dutch. I tried adding it twice with the same result.
My card is actually german, from N26 bank.

Also:
- not sure that this should happen, but the same card can be added twice.
- my VAT number shows as "Your vat ID is successfully verified and registered to null at null" (maybe because it expects Netherlands VAT ID based on the card location?)

![Screenshot_2020-01-18 Account settings](https://user-images.githubusercontent.com/5655500/72671397-de034000-3a49-11ea-9918-a6f99525e8f4.png)

**Comment by adriaanvanrossum** [comment]
That's weird, Stripe thinks it's from The Netherlands:

<kbd><img width="574" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/72671453-b1035d00-3a4a-11ea-9a3a-123635b9363c.jpg"></kbd>

I think it's okay to add multiple cards, and I'm not sure how to prevent doubles. Sometimes only the expiry date has changed and I don't want to store anything of cards in my database.

We fixed the null issue: https://simpleanalytics.com/account

**Comment by adriaanvanrossum** [comment]
Updated your country, it should now show info for Germany.

**Comment by alinacsava** [comment]
For the null issue: Thanks!

About Stripe: Indeed weird. And no details, name, address, it should be all there, address would actually fix their incorrect location. Is there something I can do about that? Or will details show only when I'll make a payment?

**Comment by adriaanvanrossum** [comment]
Do you still see Dutch text on your [account page](https://simpleanalytics.com/account)? If so I need to update some code. If you see test for the VAT, you are fine.

Not sure how Stripe does get this data, it's not super accurate. I have had more customers that where targeted in the wrong country. For Dutch TAX it's okay to trust that info, but it's sometimes a bit weird for customers.

We should add a link there saying: "Is this not your country? Contact us to change it."

**Comment by alinacsava** [comment]
I don't see the Dutch text anymore, but the VAT ID section is completely gone.
Card still has "MasterCard from NL" written in front of it though.

Yeah, the link would be a good idea.

**Comment by adriaanvanrossum** [comment]
Done:

![CleanShot 2020-01-19 at 02 07 36@2x](https://user-images.githubusercontent.com/1079135/72672819-c5eaeb00-3a60-11ea-9a7a-40e6cd44abe2.jpg)
