### ISSUE TITLE
Cannot download invoice

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#216]
Invoices are missing the download link

<img width="380" alt="Screenshot 2020-01-18 at 23 35 41" src="https://user-images.githubusercontent.com/5655500/72671482-66ceab80-3a4b-11ea-94f4-48a7a69f0a91.png">

**Comment by adriaanvanrossum** [comment]
Thanks for reporting, could you try again? I believe it's now fixed, but I'm don't have a live subscription myself so would love to know if you are able to see the download link now.

**Comment by alinacsava** [comment]
I checked now, it works. Issue can be marked as fixed. Thanks!
