### ISSUE TITLE
Display all pages in Top Pages with pagination

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#220]
For one of my projects https://simpleanalytics.com/fontsarena.com the Top Pages list stops at a page with 227 views. Given that it's a content website, I'd like to have a full list of pages.

So my feature request is **paginated Top Pages** so that all are viewable.
I thought pagination scales ok, it's easiest to navigate, and wouldn't need its own separate page or new design. But "load more" button after each 100 items with infinite scroll or any solution would be greatly appreciated.

**Comment by adriaanvanrossum** [comment]
Cool, let's do this. Linked to https://github.com/simpleanalytics/roadmap/issues/206

**Comment by alinacsava** [comment]
Hi Adriaan. Is there an ETA for this? I get requests from font authors that want to know how their font fared on fontsarena.com (downloads or pageviews), but I'm not able to answer them since I can only see a very small number of pages listed in Top Pages and I didn't get into Events beta.

**Comment by adriaanvanrossum** [comment]
I expect this to happen in the next month! Please bug me when we didn't ;)

**Comment by alinacsava** [comment]
That's good news. Sorry for the late reply, I was away.

**Comment by alinacsava** [comment]
You said to bug you, so I am :)

**Comment by adriaanvanrossum** [comment]
Is this something you will work on @hellodeibu? I remember you saying something about it. Would be great if I can pass this responsibly on to you ;)

<img src="https://user-images.githubusercontent.com/1079135/78290022-5c3c9200-7523-11ea-8bfd-2a8478e66fa0.gif" width="100%">

**Comment by hellodeibu** [comment]
@adriaanvanrossum I'm on it!

**Comment by hellodeibu** [comment]
This is now implemented and live! You're now fully able to browse through all **Top Pages** as-well as **Referrals**! :)
