### ISSUE TITLE
Hidden date picker after footer occupies space

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#223]
On project page (for example https://simpleanalytics.com/simpleanalytics.com), the calendar picker prevents the footer to be at the bottom of the page.

<img width="1659" alt="Screenshot 2020-01-23 at 23 40 54" src="https://user-images.githubusercontent.com/5655500/73030738-89d9d080-3e3a-11ea-8671-8c117e679450.png">

It's a problem in Firefox and Chrome, on Safari seems to be ok.

**Comment by adriaanvanrossum** [comment]
Thanks! We have fixed this in our code, but not deployed yet. Will be deployed when the now online popover is done. Hopefully tomorrow! Will keep this open until then.

**Comment by adriaanvanrossum** [comment]
Fixed now!
