### ISSUE TITLE
Enable compression and caching

### ISSUE THREAD

**Issue by Macro-Jackson** [simpleanalytics/roadmap#230]
Google Page Speed suggesting:
Opportunities: These suggestions can help your page load faster.
Enable text compression: 0.15 s
Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes

URL: /app.js
Size 4 KB
Potential Savings 2KB

**Comment by LeCodeCo** [comment]
Should be as simple as a change to the webserver config. This is easy to do with Nginx.

**Comment by adriaanvanrossum** [comment]
We use [Server Side Includes (ssi)](https://nginx.org/en/docs/http/ngx_http_ssi_module.html) to include the hostname of the file. That's probably why it doesn't work right now. We will move this server to Amsterdam soon, so we will fix this then as well.

- https://stackoverflow.com/questions/49590415/nginx-with-memcache-gunzip-and-ssi-dont-working-together

Test it with `curl -H "Accept-Encoding: gzip" -I https://sa.nomadlist.com/app.js`

**Comment by adriaanvanrossum** [comment]
Reported by @Jivings:

> I think a couple of things are mis-configured with the script caching. 
> The expire age is only set to 1 hour (seems quite low);
> 
> ```cache-control: max-age=3600```
> 
> There's no last-modified or e-tag header (meaning the browser can't invalidate the cache efficiently).
> 
> <img width="486" alt="image" src="https://user-images.githubusercontent.com/1462828/74408028-3819da00-4e2b-11ea-8e03-f033675078b5.png">

**Comment by adriaanvanrossum** [comment]
Fixed!

```
$ curl -H "Accept-Encoding: gzip" -I https://sa.nomadlist.com/app.js
HTTP/2 200 
server: nginx
date: Fri, 29 May 2020 11:45:49 GMT
content-type: application/javascript
vary: Accept-Encoding
expires: Fri, 05 Jun 2020 11:45:49 GMT
cache-control: max-age=604800
pragma: public
cache-control: public
strict-transport-security: max-age=31536000; includeSubDomains
content-encoding: gzip
```

`max-age` is set to `604800` (7 days) and `content-encoding` to `gzip`.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1079135/83256329-8ec8db00-a1b2-11ea-9469-0990932bfb11.png">

https://www.giftofspeed.com/gzip-test/
