### ISSUE TITLE
Content outside of page

### ISSUE THREAD

**Issue by Macro-Jackson** [simpleanalytics/roadmap#231]
On mobile there is a problem where content is creating a wider page then allowed.

![Screenshot_2020-01-27-21-17-17-013_com android chrome](https://user-images.githubusercontent.com/21694411/73210497-b3e90680-414a-11ea-8cce-78264dae0f64.jpg)

**Comment by adriaanvanrossum** [comment]
Thanks for letting us know! We will fix this.

**Comment by adriaanvanrossum** [comment]
@Macro-Jackson: fixed! It was an issue with the date picker. If it's overflowing on small screens it would be invisible but not hidden. Now it's hidden when it's not open. Thanks for reporting!
