### ISSUE TITLE
Implement Elasticsearch for easier analytics

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#243]
This summer we are planning on working on a Elasticsearch app where we can ask all kind of analytics metrics from. We need it for a few features.

We hope @Jivings will help us!

Related issues
- https://github.com/simpleanalytics/roadmap/issues/240
- https://github.com/simpleanalytics/roadmap/issues/188
- simpleanalytics/roadmap#166
- https://github.com/simpleanalytics/roadmap/issues/100

**Comment by Macro-Jackson** [comment]
We have quite some experience here. If you have questions we might be able to help out.

**Comment by adriaanvanrossum** [comment]
Thanks @Macro-Jackson! Will probably ask some questions when we start.

**Comment by adriaanvanrossum** [comment]
### Schema

A specification of the requirements for this issue.

We have a few data points linked to every page view:
1. `hostname` (id linked to websites)
1. `path` (string like `/product/123`)
1. `referrer` (string of `document.referrer`)
1. `session_uuid` (uuid of session)
1. source
   - `utm_source`, `ref`, `source`
   - `utm_medium`, `medium`
   - `utm_campaign`, `campaign`
1. user agent
   - `browser_name`
   - `browser_version`
   - `os_name`
   - `os_version`
1. device
   - `desktop`
   - `tablet`
   - `mobile`
1. `country` (2 letter ISO)
1. `unique` (boolean)
1. `scolled`* (integer from 0 to 100)
1. `duration`* (integer in seconds)

\* These types are added when the visitor closes the page via `session_uuid`.

### Data queries

With this schema we want to get answers on these questions:
- Visits over time grouped by days/weeks*/years* (unique and non unique)
- List of referrers sorted by most visits (unique* and non unique)
- List of paths sorted by most visits (unique* and non unique)
- List of paths sorted by a formula based on `scrolled` and `duration` *
- List of user agents sorted by most visits (unique* and non unique)
- List of countries sorted by most visits (unique* and non unique)

For referrers
- Visits over time based on a referrer
- List of paths sorted by most visits based on a referrer *
- List of paths sorted by a formula based on `scrolled` and `duration` based on a referrer *
- List of user agents sorted by most visits based on a referrer *
- List of countries sorted by most visits based on a referrer *

For paths
- Visits over time based on a path
- List of referrer sorted by most visits based on a path *
- List of user agents sorted by most visits based on a path *
- List of countries sorted by most visits based on a path *

For user agents, countries, ...
- ...

\* Questions we can't answer in our current system

> All these queries should keep the a time zone in mind. If a user gets the same data for Monday from New York it's probably different from the person getting it for Amsterdam. In the current app we solved this by aggregating per hour. That way we can always get all records between certain hours (a.k.a. time zones).

### How?

I'm thinking of setting up a different server with just Elastic Search and a Node.js app which will serve as an API. So all data will be aggregated on the Elastic Search server and send back to the main server where we display the data.

Would be a nice-to-have if we could add authentication there as well, so people and our front end can "talk" directly to the Elastic Search server.

**Comment by adriaanvanrossum** [comment]
Added two utm codes to the source:

   - `utm_content`
   - `utm_term`

**Comment by Jivings** [comment]
Do you have any thoughts about this;

> List of paths sorted by a formula based on scrolled and duration based on a referrer *

I'm terming this "most popular paths", I think that's what it means essentially yes?

If possible it would be better to calculate this at index time if you have an idea of how it will work.

**Comment by adriaanvanrossum** [comment]
> List of paths sorted by a formula based on scrolled and duration based on a referrer *

It means it will use the two other variables: `scrolled` and `duration`. The output will be a list of "best quality pages" or something. The list will live next to the list of "most popular paths".

I can image the formula being something like this:

```js
scrolled * Math.min(duration, 300) * 0.5
```

The list items are comparable to each other so if the highest score is `349` then we convert that to `100%` and the other items relative to that. So the final list would be something like:

| page      | score_raw | score_percentage |
|-----------|----------:|-----------------:|
| /         |       349 |             100% |
| /contact  |       290 |              83% |
| /feedback |        50 |              14% |

> If possible it would be better to calculate this at index time if you have an idea of how it will work.

The `scrolled` and `duration` variables will be added later, so not sure if the indexing happens then? It's also relative to the other list items, so maybe it should just spit out the `score_raw` and in the Node.js app we at the `score_percentage`. The only thing that's important is that we can sort on the `score_raw`. But the formula will change in the future, I'm sure.

So if we can make the sort work on a formula on `scrolled` and `duration` without storing the output in ES, that would be great. But if we need to store it, that's also fine. Then we need to update old fields when the formula changes.

**Comment by Jivings** [comment]
Okay I understand the score but not why you need the %. 

Can you give me an example of what you're trying to show in the UI? Is it;

1. The top N paths by quality 
2. The top 5th (/25th/50th etc) percentile of paths  

If 1 is what you want then the `score_percentage` is just some way of represnting the score on the FE, then we can do a regular aggregation to get the top N paths, and also return the total & sum of the scores so you can calculate the % at query time.

If you want to get the percentile (I could see this maybe is useful for finding outliers, like REALLY popular or unpopular paths), then we can support that via a [percentile aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html) on the `score_raw` field.

**Comment by adriaanvanrossum** [comment]
I think it's closer to 1 for now. Quality would be nice if we represent that with a percentage but I'm totally fine to do this in the app itself. Then we just have a score relative to the other pages for that period.

The result in the dashboard would be an indicator (not sure yet on how to show this, maybe with green, orange, or red color dot) next to the page name in the list. Something simple where people can see: "ah, this page is doing well."

**Comment by adriaanvanrossum** [comment]
Elasticsearch is up and running. Most bugs are in the frontend and we have open issues for those. No need for this issue anymore. 🥳
