### ISSUE TITLE
Page title website dashboad

### ISSUE THREAD

**Issue by Macro-Jackson** [simpleanalytics/roadmap#255]
Suggestion: on the website analytics page the page title is "Simple Analytics - Simple, clean, and privacy-friendly analytics"

But if you make a link out of this on your mobile or if you leave this open in your browser or if you bookmark this page then you can't see it is your Analytics home page. So I would suggest to change it to one of the following options:
#websitename# - Simple Analytics
Simple Analytics - #websitename# (not preferred as Chrome and other browsers mostly have ~20 characters in the tab shown.)
Analytics for #websitename# (not preferred, see above reason)
#websitename# (as the favicon already stands for Simple Analytics)

**Comment by adriaanvanrossum** [comment]
<kbd><img width="348" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/75158191-e4a26880-5715-11ea-9a52-31409ccf1925.jpg"></kbd>

**Comment by adriaanvanrossum** [comment]
It's now on live. With one exception: https://simpleanalytics.com/simpleanalytics.com, because people will not bookmark those and "Simple Analytics" looks cleaner than "simpleanalytics.com" at first sight.

Thanks for the suggestion!

**Comment by Macro-Jackson** [comment]
Superb! My suggestion to use the website name instead of the website address still stands. As you mention it looks cleaner.

**Comment by adriaanvanrossum** [comment]
How would we get the website name? I think it's hard to get this info correctly for every website, no?

**Comment by Macro-Jackson** [comment]
Just add it as a setting to the Simple Analytics website here:
https://simpleanalytics.com/simpleanalytics.com/settings
So the user can fill it in. If it isn't filled in you can always fall back to the website address.

**Comment by adriaanvanrossum** [comment]
Ah I see. That would be fun, but if that's the only purpose I wouldn't want to add the extra field in the settings page. If there are more locations pupping up I might add it.
