### ISSUE TITLE
Let visitors of customer dashboards use their referral link

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#294]
When new visitors land on the public dashboards of customers, we should show a link to signup that uses the referral link/code of that customer (if they have any). That way customers profit and have extra incentive to share the public dashboard.

Thanks @Jivings for this suggestion!

**Comment by hellodeibu** [comment]
This is now implemented! If you have a referral link set up, the _Sign up to add your website_ button that is shown to new users visiting your public page will automatically use your referral link :).

**Comment by adriaanvanrossum** [comment]
I think we should add a little text below the button or something that people directly see it's a referral link.
