### ISSUE TITLE
Create CloudFlare app

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#30]
Thanks to @daniellockyer and @jessemsz via Twitter

**Comment by fertila** [comment]
What would this do exactly?

**Comment by adriaanvanrossum** [comment]
If customers use CloudFlare they could enable a Simple Analytics app that does send requests to our servers without the need for JavaScript. This would be very easy for our customers I think.

Some more info:
- https://www.cloudflare.com/apps/developers
- https://www.cloudflare.com/apps/developer/dashboard

**Comment by adriaanvanrossum** [comment]
Today @daniellockyer and I created a CloudFlare app. It incapeble of recoding `<noscript>` vistis, but it's super fast in loading the JS.

**Comment by adriaanvanrossum** [comment]
Done: https://github.com/simpleanalytics/roadmap/issues/185
