### ISSUE TITLE
The columns look a bit funny on mobile

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#307]
With a screen of 375px: 

<kbd><img width="375" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/80922221-da3ac580-8d7b-11ea-95b7-4ecf03fe366f.png"></kbd>

**Comment by hellodeibu** [comment]
@adriaanvanrossum I think this one might have already been solved along the way -- could you let me know if it still appears funny for you, and if so, on what device that might be so I can take another look? Thank you kindly!

![image](https://user-images.githubusercontent.com/18850/108452852-9e420400-72ac-11eb-9905-9621d93421e6.png)

**Comment by adriaanvanrossum** [comment]
Nice, love it when things are fixed without knowing :)
