### ISSUE TITLE
Do-Not-Track header not observed with GIF

### ISSUE THREAD

**Issue by FMCorz** [simpleanalytics/roadmap#312]
It appears that the `DNT` header is not observed when collecting data from the GIF.

```
GET /noscript.gif?timezone=Etc%2FUTC&unique=true&hostname=example.com&path=%2Fexample%2Fpath&https=true HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
DNT: 1
Host: queue.simpleanalyticscdn.com
User-Agent: HTTPie/0.9.9

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Type: image/gif
Date: Tue, 05 May 2020 05:30:34 GMT
Expires: 0
Pragma: no-cache
Server: nginx
Simple-Analytics-Feedback: Thanks for sending this page view!
Simple-Analytics-Location: Amsterdam
Strict-Transport-Security: max-age=15768000
Transfer-Encoding: chunked
```

The above request appeared on my dashboard, and the `Simple-Analytics-Feedback` header also confirms that the request was accepted. I understand the DNT situation is unclear but as the documentation states that:

> [...] by default we skip requests with the Do Not Track enabled. The stats will not include visitors with the Do Not Track enabled.

I think it makes sense to skip those requests too, unless an additional parameter equivalent to the HTTP attribute `data-skip-dnt="true"` is set, perhaps `skip-dnt=true` though my preference would go for `ignore-dnt=true`.

Thank you for your consideration!

**Comment by FMCorz** [comment]
Note, I noticed this because I bank on my own visits to be skipped as I navigate with Do-Not-Track with Firefox, but they appeared nonetheless.

**Comment by adriaanvanrossum** [comment]
Thanks for letting us know Frédéric! We just added this to our code:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/81056228-7246c500-8eca-11ea-857a-a3f357fa47f5.png"></kbd>

It might take a day or so because it's on production. Will let you know when it is.

**Comment by adriaanvanrossum** [comment]
This is now live on production @FMCorz!

**Comment by FMCorz** [comment]
Awesome, thank you for addressing this so quickly!
