### ISSUE TITLE
Order of visit count summary in weekly email may be incorrect

### ISSUE THREAD

**Issue by hellodeibu** [simpleanalytics/roadmap#331]
The weekly email should show a brief summary of where most traffic came from, sorted from highest down, but this may not always be the case. Further checking is needed to confirm this.

> You had X% more unique page views (Xk) than last week (Yk). Most traffic comes from A +Z% followed by B (etc...)

**Comment by adriaanvanrossum** [comment]
<kbd><img width="250" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/83393800-b2c92e00-a3f7-11ea-8bd9-fb663d4db4fa.png"></kbd>

<kbd><img width="500" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/83393811-b8267880-a3f7-11ea-8cbf-8e1a8980a292.png"></kbd>

**Comment by adriaanvanrossum** [comment]
I checked this again today and it all looks correct!
