### ISSUE TITLE
Have Refreals Be More Working

### ISSUE THREAD

**Issue by IamTregsthedev** [simpleanalytics/roadmap#334]
Right Now, Refreals don't work as they ars suposed to!

  
Some /?ref=links links don't even work!

**Comment by adriaanvanrossum** [comment]
What exactly are you trying with the `/?ref=link`?

**Comment by IamTregsthedev** [comment]
To see where my data comes from

When I try thefundamentals.xyz/?ref=test

It doesn't work even on icongito or new browser

Sent out to a few people to test

**Comment by adriaanvanrossum** [comment]
Hm, I wonder what is going on. I just tested it with http://watiseropderadio.nl/?ref=adriaan-test and you see it in the dashboard:

<kbd><img width="221" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/83739773-51eb6100-a656-11ea-8eb3-f22cbff44293.png"></kbd>

https://simpleanalytics.com/watiseropderadio.nl

Incognito browsing is usually more strict than normal browsing. We block for example visits when DNT is enabled. You can disable this behavior though: https://docs.simpleanalytics.com/dnt

Would you mind checking what shows in your browser console?

![image](https://user-images.githubusercontent.com/1079135/83740166-c3c3aa80-a656-11ea-92ce-471eec2345d8.png)

**Comment by IamTregsthedev** [comment]
I've given the link to a few people, and it doensnt work. I can share my console

Just chcked, DNT is enabled. But Wheb I sent to other people, it didn't work

I have google running as wrll, maybe THat's it?

**Comment by adriaanvanrossum** [comment]
If they have DNT enabled it will not show up either. Could that be the case? You can run Google next to SA without any problems. We don't interfere with each other. If the people you did send it to have DNT enabled it makes sense. Otherwise it's something else.

Make do a test with DNT disabled with your script? Just add `data-skip-dnt="true"` to your script tag: https://docs.simpleanalytics.com/dnt

**Comment by IamTregsthedev** [comment]
I've added this, and refreals are back, thanks so much:)
