### ISSUE TITLE
Update the Wordpress plugin

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#365]
Update to the latest script version and maybe add a settings option to specify URLs when using custom subdomain.

**Comment by adriaanvanrossum** [comment]
You could install the non-official plugin if you want: https://docs.simpleanalytics.com/wordpress-plugin-by-refined-practice

**Comment by alinacsava** [comment]
I've made a custom version for my use, but I saw the plugin has 100+ active installations, not all its users will see this answer.

**Comment by adriaanvanrossum** [comment]
We also updated the plugin to use our latest script!

**Comment by alinacsava** [comment]
> We also updated the plugin to use our latest script!

Yeah, I forgot to mention that I closed the issue because I saw the update. :)
