### ISSUE TITLE
Overflow issue with ellipsis

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#369]
thanks to @Amritnagi

![image](https://user-images.githubusercontent.com/1079135/89202668-9a21f380-d5b3-11ea-84f9-cb5d2219a31e.png)

adding this seems to remove it:

![image](https://user-images.githubusercontent.com/1079135/89202682-9db57a80-d5b3-11ea-8dfe-ba083d7caad9.png)

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1079135/89204854-110cbb80-d5b7-11ea-8276-8cf65b8f448d.png">

Related to https://github.com/simpleanalytics/main/pull/116

**Comment by hellodeibu** [comment]
I've applied a `line-height: 180%` specifically to the .vue-ellipsis class. I'm actually not 100% sure in which browser this occurs so can't confirm if this fixes things. We'll have to ask Amrit what browser/os he's using and if this resolves it.

**Comment by amritnagi** [comment]
I'm using Chrome 84.0.4147.105 on Windows 10.

Let me know an updated link and I can retest for you.

________________________________

**Comment by hellodeibu** [comment]
Nice, thanks @amritnagi! Adriaan will be pushing the proverbial button when he gets a chance, so either he or I will definitely give a ping once it's live again, probably in the Telegram group (too). Cheers!

**Comment by hellodeibu** [comment]
Hi @amritnagi! The aforementioned fix has been deployed together with other updates. Could you let me know if the problem persists for you, or if this has resolved it? Thanks so much!

**Comment by tailwindtoolbox** [comment]
<img width="421" alt="9314E5A5-04AE-4BE9-9C33-EA323DE2815B" src="https://user-images.githubusercontent.com/43570497/95963427-96a2b800-0dff-11eb-825b-9f65159c7c60.png">

Looking good now 👍🏽

**Comment by amritnagi** [comment]
<img width="421" alt="B00BC92E-3938-47D0-A688-64840A30A01A" src="https://user-images.githubusercontent.com/25029371/95963583-c782ed00-0dff-11eb-9389-05c95c25d54f.png">

Looking good now 👍🏽

**Comment by adriaanvanrossum** [comment]
Awesome!
