### ISSUE TITLE
Site badges are broken on beta

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#374]
https://beta.simpleanalytics.com/badges

**Comment by adriaanvanrossum** [comment]
Low prio because this is a beta only issue I think.

**Comment by alinacsava** [comment]
The issue is with the "Copy html" buttons. If the badge code is manually copy-pasted works fine. But if it's copied using the buttons, the code has the urls with http://localhost:3000 instead of https://simpleanalytics.com

**Comment by hellodeibu** [comment]
Fixed and should be available once the new version is deployed!
