### ISSUE TITLE
Graph shows incorrect days

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#375]
> for some reason when I select a data for 1 month, then it shows data for 32 days, same with week 8 days.

**Comment by adriaanvanrossum** [comment]
Also:

> 1 month in less than 1 month.

via Khodl

**Comment by hellodeibu** [comment]
Could you tell me what this is referring to?

> 1 month in less than 1 month.

And it might be necessary to create a separate (non-beta specific?) feature request for the second idea, as it's quite different from the issue reported I think, right?

**Comment by adriaanvanrossum** [comment]
I think it's about this issue:

<kbd><img width="100%" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/92124566-397a1680-edfe-11ea-976c-71ffa6da9130.png"></kbd>


Added new issue for the second part: https://github.com/simpleanalytics/roadmap/issues/395
