### ISSUE TITLE
Hover over referers does not work

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#386]
<kbd><img width="820" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/91280886-b4e92180-e787-11ea-8d5c-d178823439c8.png"></kbd>

<kbd><img width="820" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/91280889-b6b2e500-e787-11ea-866f-782414730077.png"></kbd>

**Comment by hellodeibu** [comment]
I deliberately left this functionality out as filtering is now possible on more than just referrer (and pages), but I think with what is mentioned in #395 (and #378) showing data on-hover is no longer needed as actually making the selection should show data alongside the non-filtered data, right?

**Comment by adriaanvanrossum** [comment]
>  showing data on-hover is no longer needed as actually making the selection should show data alongside the non-filtered data, right?

Yes

**Comment by hellodeibu** [comment]
This is now superseded by the new comparative graph functionality that lets you filter on multiple types at once (e.g. both referrals and pages) too and available once the new beta version is deployed! :)
