### ISSUE TITLE
Keep scale when filtering

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#395]
> When filtering, I didn't expect the time scale (1 month) to be adjusted to the traffic (because the first view was less than 1 month ago). And it's then hard to compare graphs.

copied from https://github.com/simpleanalytics/roadmap/issues/375

I do think this is a beta issue because if you view 1 month of data and you filter for 1 referral you want to see how that compares to that 1 month of data. In the current app it's clear how much it is off the total graph:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/92124855-94137280-edfe-11ea-80de-48f32a64291f.png"></kbd>

**Comment by hellodeibu** [comment]
If I understand this correctly, this basically means the idea is to change the behavior of the graph to show an additional data set based on the selections made along with the initial graph, kind of like how in the currently live version when you hover over referrals it shows a separate data set, although not on-hover anymore of course, as you can filter based on multiple data types. This would take care of what is mentioned in the comment on #378 (keeping the graph's scale the same even after making selections) while still being able to adjust the graph's scale when hiding page views and only showing visitors.

**Comment by adriaanvanrossum** [comment]
Yeah, I think it's important to not add regressions on how people use our tool at the moment. The hover is fast and easy to read, would love to have the new app also be fast and able to compare to total visits. Don't you think?

**Comment by adriaanvanrossum** [comment]
This is done, right?

**Comment by hellodeibu** [comment]
Yes it is! :)
