### ISSUE TITLE
When filtering, users = views in the graph

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#402]
![lala](https://user-images.githubusercontent.com/1079135/92734921-40aea080-f379-11ea-9c16-e1e34be6dc2b.gif)

Here is a bug in the beta. When filtering, users = views in the graph.

via Khodl

**Comment by hellodeibu** [comment]
@adriaanvanrossum this is actually because the data for visitors and page views is roughly identical when filtering on a specific referrer, which means the two data sets look so similar you can barely tell them apart. Unless I misunderstood the bug report though, if so please let me know so I can look into it :)

**Comment by Khodl** [comment]
The "roughly" would be "exactly" if you're not able to associate the original referrer during the second page view by the same user.

In this case, my suggestion would be to hide the page views and only show visitors (or vice-versa), as it's currently the case.

**Comment by hellodeibu** [comment]
I've pushed a change in behavior that hides both the page views dataset and checkbox (and enables "visitors" if it wasn't already) if a referral is being filtered on. This'll become available with the next deploy! :)

**Comment by adriaanvanrossum** [comment]
What should happen when the referral and paths for example are filtered? Not very important for now, but something to keep in mind for the future.

**Comment by hellodeibu** [comment]
@adriaanvanrossum if a referrer is being filtered on, all page views and visitors data will be identical, as subsequent refreshes or visits back to the same page (page views) are not attributed to the referrer being filtered on. So if someone is filtering on more than one thing, so long as referrer is one of them, this behavior should remain the same, right?

**Comment by adriaanvanrossum** [comment]
Ah, good thinking. Thanks.
