### ISSUE TITLE
Data differences between current and beta

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#415]
Current version 41,884 visitors
<img width="1045" alt="Screenshot 2020-09-24 at 20 54 35" src="https://user-images.githubusercontent.com/5655500/94187588-6f179a00-fea8-11ea-8f16-802b71876ac1.png">

Beta 40,444 visitors
<img width="1036" alt="Screenshot 2020-09-24 at 20 54 50" src="https://user-images.githubusercontent.com/5655500/94187626-7e96e300-fea8-11ea-83a0-b9d8c71417dc.png">

**Comment by adriaanvanrossum** [comment]
Thanks. What time zone are you using in the dashboard?

**Comment by alinacsava** [comment]
Europe/Berlin

**Comment by adriaanvanrossum** [comment]
Are you okay if we look at your data to she what is going on?

**Comment by alinacsava** [comment]
Sure, no problem.

Alina

**Comment by adriaanvanrossum** [comment]
Cool, I didn't know it was public: https://simpleanalytics.com/fontsarena.com. Thanks!

**Comment by alinacsava** [comment]
Yes, just the top pages are hidden

Alina

**Comment by adriaanvanrossum** [comment]
The difference is very visible:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/94684574-87643a80-0328-11eb-9b1c-16d3396d7a7c.png"></kbd>

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/94684585-89c69480-0328-11eb-9c2e-f3e4fe7d0119.png"></kbd>

I figured out why this happens. It's not easy to fix, but we are going to of course.

Thanks Alina!

**Comment by adriaanvanrossum** [comment]
Actually the new database is right. The double visits are coming from Google bots. They don't identify as Google bots. We are going to detect them with a predefined list of bots. That way they will never show up in any of our databases.

**Comment by adriaanvanrossum** [comment]
Fixed.
