### ISSUE TITLE
Deleted traffic shows in weekly summary

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#417]
I deleted the traffic from a certain referrer, but it's mentioned in the weekly summary

**Comment by adriaanvanrossum** [comment]
Can it be that it shows it now in the dashboard as well? That they again pushed some traffic to your website?

If so we might block them for all customers. What is their referrer?

**Comment by alinacsava** [comment]
You're right, there was new traffic. It was on page 2 of Referrals and I didn't notice. 
I'll write the referrer on telegram, here it's too public. :)

**Comment by adriaanvanrossum** [comment]
They are now blocked on NGINX level. Could you delete that data with the referral? Then we can see if I did implement the block correctly. Please report back if you see them again.

**Comment by alinacsava** [comment]
Thank you, Adriaan! I deleted the traffic.
