### ISSUE TITLE
Merge master branch into beta branch

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#422]
I think this can be quite some work as we changes a lot in both branches.

Would you mind taking a look @hellodeibu? Not sure if we should do this at the end only. But it would be nice to have the master changes visible in the beta branch as well.

**Comment by hellodeibu** [comment]
Merged everything! It'll be good to take a good look to make sure everything still works as it should as indeed quite a few things changed, but so far things are looking alright. It's really nice to see the new main navigation you made show up together with the new beta! :)

**Comment by hellodeibu** [comment]
...going to leave this one open for a moment, as a reminder that we should check the key parts of the system. There were some changes in the email system too (the one allowing customers to have email reports sent to more than one email address), perhaps you could take a peek there and run a test or two to make sure everything is still in order?

**Comment by adriaanvanrossum** [comment]
Tested and done.
