### ISSUE TITLE
Numbers get cut when not using data rounding (beta)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#431]
<img width="361" alt="Screenshot 2020-10-09 at 22 19 33" src="https://user-images.githubusercontent.com/5655500/95628457-60bba780-0a7e-11eb-8596-414cd8fa3272.png">

**Comment by adriaanvanrossum** [comment]
This is still an issue with the latest beta version:

![image](https://user-images.githubusercontent.com/1079135/96048496-02743780-0e77-11eb-88db-f1d2ecfdfa12.png)

**Comment by adriaanvanrossum** [comment]
While you are at it, would you mind making these the same alignment?

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96166093-cba52c80-0f1d-11eb-9a35-8d07fed3e51d.png"></kbd>

**Comment by hellodeibu** [comment]
This should be fixed now, pending deploy!

**Comment by adriaanvanrossum** [comment]
Lovely, also the more space helps the page breathing:

<kbd><img width="753" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96229660-87ef0900-0f97-11eb-87e0-7650869815d8.png"></kbd>
