### ISSUE TITLE
Today/Week/Month/3 Month/Year broken (beta)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#432]
Each hard refresh & retry reports a random number of days and visits. Screen captures here: https://t.me/c/1188685865/2150

**Comment by hellodeibu** [comment]
We already discussed this in the Telegram group, but for anyone else following here, this has been fixed already and is pending a deploy. See also #425. Thank you kindly for reporting! :)

**Comment by adriaanvanrossum** [comment]
This has been deployed and should be working!

**Comment by alinacsava** [comment]
All works flawless now, I'll close this and #433
