### ISSUE TITLE
Date interval text gets cut (beta)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#433]
Beta has prev/next arrows that take space, so 1 digit gets cut when selecting a date interval.

<img width="315" alt="Screenshot 2020-10-13 at 10 08 45" src="https://user-images.githubusercontent.com/5655500/95840604-a4473780-0d44-11eb-8ae3-5d7123bd6568.png">

<img width="305" alt="Screenshot 2020-10-13 at 11 10 17" src="https://user-images.githubusercontent.com/5655500/95840651-b6c17100-0d44-11eb-965a-6daf9f660352.png">

**Comment by hellodeibu** [comment]
I seem to have never actually created an issue for this one, but it has also already been fixed and is pending deploy. I should've made an issue about this, apologies. Thanks to you we've got an issue for it now though! :)

**Comment by adriaanvanrossum** [comment]
I will keep this issue open for now. Will let you know when I did deploy the latest version @alinacsava! Still working on the data migration. Almost there!

**Comment by alinacsava** [comment]
Thanks, Adriaan. I will wait for the latest version. I hope all goes smooth!

**Comment by adriaanvanrossum** [comment]
Just deployed the latest beta version with it's new data. Love to hear if this works for you now.

**Comment by alinacsava** [comment]
All ok now, this is fixed and also #432 Thanks @adriaanvanrossum and @hellodeibu
