### ISSUE TITLE
When going to utmSources=email the tab is not selected and filter kind of active

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#435]
http://localhost:3000/simpleanalytics.com?from=2020-09-16&to=2020-10-15&utmSources=email&agents=Chrome

![image](https://user-images.githubusercontent.com/1079135/96143127-1b2a2f00-0f03-11eb-84c4-45bd36f409ba.png)

**Comment by hellodeibu** [comment]
The bug where on reload the UTM source filter wasn't properly being applied should be fixed now! 

For the other point, I have added a check that if you (re)load the dashboard with an UTM source and no referral filter applied, it will automatically start with the UTM sources "tab" open. Do you think that works well enough? Or do you also want to have it load with the UTM sources tab open even if you have also filtered on a referral?

**Comment by adriaanvanrossum** [comment]
Works great now!
