### ISSUE TITLE
Referral pagination buttons are not visible after the last page

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#436]
Demonstration:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96166575-6f8ed800-0f1e-11eb-847d-aac3485dd9ef.gif"></kbd>

**Comment by adriaanvanrossum** [comment]
And maybe not show them at all when the list is not long enough.

<img width="657" alt="image" src="https://user-images.githubusercontent.com/1079135/96171517-53426980-0f25-11eb-8e93-a7d72267df19.png">

**Comment by hellodeibu** [comment]
This should be fixed now!
