### ISSUE TITLE
Put back the icons from the current website

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#437]
Beta:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1079135/96172035-1460e380-0f26-11eb-9e1c-401bc39aac42.png">

Current website:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1079135/96172043-16c33d80-0f26-11eb-8808-553c1779b6e8.png">

So just removing the "beta" part and update the icons.

**Comment by hellodeibu** [comment]
This should be fixed now!
