### ISSUE TITLE
Referral Highlights do stay visible when not filtered

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#438]
![image](https://user-images.githubusercontent.com/1079135/96172516-df08c580-0f26-11eb-8d1d-e528dd84d4c0.png)

**Comment by adriaanvanrossum** [comment]
![image](https://user-images.githubusercontent.com/1079135/96173897-cef1e580-0f28-11eb-8203-0759e5b451aa.png)

**Comment by hellodeibu** [comment]
This should be fixed now!
