### ISSUE TITLE
"Remove filter" text overlaps top pages title (beta)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#439]
<img width="389" alt="Screenshot 2020-10-15 at 15 55 47" src="https://user-images.githubusercontent.com/5655500/96153053-8547d180-0f0d-11eb-85e0-678159002461.png">

**Comment by adriaanvanrossum** [comment]
This will be fixed in the next version, thanks!

**Comment by adriaanvanrossum** [comment]
Fixed in latest version. Deployed!
