### ISSUE TITLE
Chart stays empty on load when filtering on referral

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#440]
http://localhost:3000/watiseropderadio.nl?from=2020-09-16&to=2020-10-15&referrals=watiseropderadio.nl

**Comment by hellodeibu** [comment]
I'm having trouble reproducing this, but I have a few ideas/questions:

1. Technically we shouldn't be able to filter on the same domain name, right? It used to be removed from view but it seems to have popped up again
2. In your case, were the "visitors" and "compare filtered" checkboxes selected? Or was "Page views" marked as selected in your cookie?

**Comment by adriaanvanrossum** [comment]
I can reproduce this, so I think we are good. Let's keep an eye on it.
