### ISSUE TITLE
When clicking on a normalized referrer hostname you can't see mini websites

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#441]
When I click on `google` (a normalized referrer hostname) you don't have the full address. So the overview of mini websites should show the list with the raw referrer hostname, I think.

![image](https://user-images.githubusercontent.com/1079135/96226345-c46c3600-0f92-11eb-951d-4bd3f8f66156.png)

**Comment by hellodeibu** [comment]
This is actually a bit of a tricky one, as there's no direct correlation between `referrer.hostname.raw` and `referrer.path.raw` when searching for them both.. This probably needs an ES API change to make it work with these normalized referrer types. Trying to look into it a bit more, but wanted to share this in advance so you know what might be needed for this.

**Comment by adriaanvanrossum** [comment]
Fixed in latest version.
