### ISSUE TITLE
Make decimals not show above 1%

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#443]
Just like countries and browsers, we should not show 34.6% but 35%.

![image](https://user-images.githubusercontent.com/1079135/96228928-8a9d2e80-0f96-11eb-9bba-b30b339a1270.png)

**Comment by hellodeibu** [comment]
Should be fixed now!

![image](https://user-images.githubusercontent.com/18850/96234006-cefaef80-0fd3-11eb-82da-5ad89965c26f.png)
