### ISSUE TITLE
Browser navigation buttons don't work when drilling down into the chart

### ISSUE THREAD

**Issue by Jivings** [simpleanalytics/roadmap#444]
Steps to reproduce;

1. Load page https://simpleanalytics.com/simpleanalytics.com
2. Click day on chart, chart updates to show that days data 👍 
3. Click browser back button
4. URL changes but chart doesn't update

Expected;

- Chart should update to show original unfiltered data

Browser info;

Firefox 81.0.2 (64-bit)

**Comment by hellodeibu** [comment]
Can confirm this, it seems like this is specific to when you're trying to go back to the initial state where no start/end dates are present in the URL. Thank you for letting us know!

**Comment by hellodeibu** [comment]
A fix is pending deploy now. Thanks for catching and reporting this!
