### ISSUE TITLE
Add "Go back" button on hide traffic page

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#445]
Would be useful to have one like we have on the website settings page.

<img width="493" alt="Screenshot 2020-10-19 at 10 41 49" src="https://user-images.githubusercontent.com/5655500/96423181-4067b780-11f9-11eb-8617-8260569aae6d.png">

**Comment by adriaanvanrossum** [comment]
We could add this to events page as well.

**Comment by adriaanvanrossum** [comment]
Work in progress:

<kbd><img width="815" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96449422-17edb680-1215-11eb-9f41-a1909020bfc2.png"></kbd>

**Comment by alinacsava** [comment]
The extra option to search for another param is a great bonus 😉
