### ISSUE TITLE
Chart shows two "today"s

### ISSUE THREAD

**Issue by Jivings** [simpleanalytics/roadmap#446]
https://simpleanalytics.com/leavemealone.app

![image](https://user-images.githubusercontent.com/1462828/96432537-4368a500-1205-11eb-84b2-cdbce7e1b8b1.png)

**Comment by adriaanvanrossum** [comment]
This is with time zone Asia/Bangkok

**Comment by Jivings** [comment]
Just a UI issue I think because the response from elastic looks fine.

**Comment by hellodeibu** [comment]
I'm having trouble replicating this; could you do me a favor and let me know a bit more information so I can try to work this out?

- What timezone is your computer (and browser, if it differs) set to?
- What timezone is your website set to? (I think this is the one that's **Asia/Bangkok**, right?)
- Around what time of day did you see this happen, or does it happen any time of the day for you?

Thank you kindly!

**Comment by Jivings** [comment]
It happened when I was in TZ Berlin and my site was set to Bangkok. It didn't seem specific to a certain time of day that I noticed, just all the time.

I'm no longer in the same TZ and it seems fine.

**Comment by adriaanvanrossum** [comment]
It still shows up: 

<kbd><img width="1093" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/98003565-27f9be80-1def-11eb-80b7-45e4a8dc04b9.png"></kbd>

Could you take a look again this week @hellodeibu?
