### ISSUE TITLE
Special characters are not found when clicking on paths

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#450]
Maybe this is the case for referrers and UTM codes as well?

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96469206-4081aa80-122d-11eb-86fb-6045f3d9396a.png"></kbd>

**Comment by adriaanvanrossum** [comment]
Related: https://github.com/simpleanalytics/roadmap/issues/451

**Comment by hellodeibu** [comment]
A fix for this is pending merge and deploy!
