### ISSUE TITLE
In graph hover visitors show twice when zero

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#455]
<img width="411" alt="Screenshot 2020-10-20 at 01 38 30" src="https://user-images.githubusercontent.com/5655500/96523182-60d55780-1275-11eb-92eb-d336690502a4.png">

For > 0 all is ok

<img width="378" alt="Screenshot 2020-10-20 at 01 43 25" src="https://user-images.githubusercontent.com/5655500/96523342-bf023a80-1275-11eb-94ea-b9646975995c.png">

**Comment by hellodeibu** [comment]
Whoops! A fix for this is pending deploy now. Thanks for catching and reporting this!
