### ISSUE TITLE
Install instructions are missing when adding a website

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#456]
When clicking from:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96601960-cca9d580-12f2-11eb-94e3-0d9b7779b624.jpeg"></kbd>

You do not get install instructions but an empty dashboard page:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96601963-cddb0280-12f2-11eb-9685-c83964e7b5fd.jpeg"></kbd>

**Comment by hellodeibu** [comment]
This should be implemented now, pending deploy!

**Comment by adriaanvanrossum** [comment]
@hellodeibu One thing though. If it has `visitsCount > 0` we assume it `hasScript` as well. Sometimes `hasScript` is not detected but if visits show up, we know it is there. Is this the case in your code as well?

**Comment by hellodeibu** [comment]
Yes I think that's done by looking solely at `totalVisits > 0` [here](https://github.com/simpleanalytics/main/commit/ba7aae8c4de7fdfc3b21dfdbdd0e71524735ebaf#diff-05ec2762d9de3f40a559a1c26739218b142789b3379572a7f6aae460ea9dbc1fR58), which I believe is how it worked originally too.

**Comment by adriaanvanrossum** [comment]
Cool!
