### ISSUE TITLE
Show "website instructions" when site does not have script/visits yet

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#461]
<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/96850487-2d522300-1457-11eb-979d-1b826aef6396.png"></kbd>

Indirectly related issue: simpleanalytics/roadmap#458

**Comment by hellodeibu** [comment]
Is it possible that these test sites had manually modified (local) DB information (ie. the hasScript set already)? When I add a new site to the currently live version the "install instructions" shows up properly.

![image](https://user-images.githubusercontent.com/18850/97380407-5157ad80-190a-11eb-9424-6d50cb64f750.png)

**Comment by adriaanvanrossum** [comment]
You are right, this is fixed!
