### ISSUE TITLE
Graph skips from 19th to today (28th)

### ISSUE THREAD

**Issue by alinacsava** [simpleanalytics/roadmap#466]
<img width="989" alt="Screenshot 2020-10-28 at 14 55 52" src="https://user-images.githubusercontent.com/5655500/97446470-bcb37680-192e-11eb-905a-378cea4b5be4.png">

The screenshot is from https://simpleanalytics.com/sava.io
The stats are not public, but you have my consent to look at the data and use it if necessary.

**Comment by alinacsava** [comment]
Forgot to mention that it's the only site I have affected by the issue. All the others are ok.

**Comment by alinacsava** [comment]
<img width="1020" alt="Screenshot 2020-11-01 at 01 58 37" src="https://user-images.githubusercontent.com/5655500/97792986-d7634500-1be5-11eb-9d10-8f1d934d53fd.png">

Update 1 nov: skip date remained the same, even though current date changed

**Comment by adriaanvanrossum** [comment]
When I go to https://sava.io, I see a request going to https://alina.sava.io/latest.js, but the domain alina.sava.io does not resolve. There is no data coming in for that domain. I think your DNS changed?

**Comment by alinacsava** [comment]
You're right, I did change the subdomain without updating my site. I fixed that now. Thanks!

Though the graph shouldn't skip those days, but show them with zero (like it does now, after fix). 
<img width="1020" alt="Screenshot 2020-11-02 at 11 56 34" src="https://user-images.githubusercontent.com/5655500/97860499-8ac15c00-1d02-11eb-8922-bc4847252631.png">

Maybe also have a notification when the subdomain is wrong?

**Comment by adriaanvanrossum** [comment]
Yeah, I think that makes sense. I think we should alert the customer when the page views dropped to zero.

**Comment by alinacsava** [comment]
Yeah, but the zero visits need to be somehow differentiated between accurate stats and those caused by incorrect implementation of the analytics script. Chances are the zero visits will be accurate stats rather than somebody making the same mistake I did.

For example newer projects or yet-to-be-launched projects that have only a landing page can have one or a few consecutive days with zero visits. And that would mean a lot of notifications sent when they shouldn't.

Maybe letting the client set per project alerts would be an easier solution? For example when traffic drops more than X% or even zero. I mean as user I would set an alert for 1 day with 50% drop for bigger projects, and let's say 7 days with zero visits for a small project where a few days with zero are not unexpected.

**Comment by adriaanvanrossum** [comment]
Yeah, or we make it "smart" and check if a user had days with zeros before.

**Comment by alinacsava** [comment]
Yep, that would be better. When it comes to alerts I tend to go slightly control-freak manual mode and forget automation...
