### ISSUE TITLE
Detect frameworks and website builders and show our app

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#470]
When customers add a new website we can do an easy check if they are using CloudFlare. The command line version is `dig nx example.com +short` which will return something like `blabla.cloudflare.com`.

We should show a message saying something about our CloudFlare app: https://www.cloudflare.com/apps/simpleanalytics

We could do the same for frontend frameworks and platforms like WordPress

```js
if(!!window.React ||
   !!document.querySelector('[data-reactroot], [data-reactid]'))
  console.log('React.js');

if(!!window.angular ||
   !!document.querySelector('.ng-binding, [ng-app], [data-ng-app], [ng-controller], [data-ng-controller], [ng-repeat], [data-ng-repeat]') ||
   !!document.querySelector('script[src*="angular.js"], script[src*="angular.min.js"]'))
  console.log('Angular.js');

if(!!window.Backbone) console.log('Backbone.js');
if(!!window.Ember) console.log('Ember.js');
if(!!window.Vue) console.log('Vue.js');
if(!!window.Meteor) console.log('Meteor.js');
if(!!window.Zepto) console.log('Zepto.js');
if(!!window.jQuery) console.log('jQuery.js');
```

**Comment by hellodeibu** [comment]
Just a thought, but it might not be possible to reliably detect frameworks as depending on how the site is built/compiled, the frameworks and related might not be globally exposed.

**Comment by adriaanvanrossum** [comment]
No, but we might be able to cover those with looking for keywords in the JS-files. We could also make it work for most cases.

**Comment by adriaanvanrossum** [comment]
We can use https://github.com/AliasIO/Wappalyzer for this.

**Comment by adriaanvanrossum** [comment]
For example with this website we know the customer is using WIX:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/1079135/115322679-2c593e80-a1b9-11eb-8c41-a66221ca6ae6.png">

keywords: analyzers, plugins, plugin,
