### ISSUE TITLE
When navigating to URL with utmSource, make sure to open the utmSource list

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#471]
It now opens with the referral section:

<kbd><img width="456" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/98389411-4ad8dc80-2054-11eb-8907-979fb4ac47d2.png"></kbd>

But it should open the utm source section:

<kbd><img width="456" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/98389471-65ab5100-2054-11eb-9037-b7487648aea2.png"></kbd>

https://simpleanalytics.com/simpleanalytics.com?start=2020-10-07&end=2020-11-06&utmSources=no%20code%20founders

**Comment by hellodeibu** [comment]
Odd, this should actually already work as you described already. Could you try opening something like this page and let me know if it shows Referrals or UTM Sources for you?

https://simpleanalytics.com/simpleanalytics.com?period=month&count=3&utmSources=no%2520code%2520founders

**Comment by adriaanvanrossum** [comment]
I think I have fixed this recently. No worries, will close!

**Comment by adriaanvanrossum** [comment]
Seems to be fixed here: https://github.com/simpleanalytics/main/commit/d3832852ffe804d202a4bded7e8696a066b24499#diff-378501a8d23e64e1b11aa72e063756b14d95eee141d7e1dc8e59ba775617cfe4R131
