### ISSUE TITLE
When filtering by path the chart moves

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#476]
all good:

![image](https://user-images.githubusercontent.com/1079135/99412374-eee44280-28f4-11eb-9d3c-cfbf5376a5f2.png)

Not good:

![image](https://user-images.githubusercontent.com/1079135/99412391-f3a8f680-28f4-11eb-9cd5-cca34494c274.png)

related: https://github.com/simpleanalytics/roadmap/issues/410, https://github.com/simpleanalytics/roadmap/issues/466

**Comment by adriaanvanrossum** [comment]
Seems to happen for UTM sources as well:

https://simpleanalytics.com/untalent.org?utmSources=email&period=month&count=3

![image](https://user-images.githubusercontent.com/1079135/99913500-5d137580-2cf8-11eb-94f0-363c737975ea.png)

**Comment by Jivings** [comment]
Is this a problem at the elastic query? Can I help at all?

**Comment by adriaanvanrossum** [comment]
I think it can be solved in the Vue app and elasticsearch. I think ES does not return zeros for periods that don't have data.

**Comment by Jivings** [comment]
You can tell elastic to pad the empty periods with zeros in the histogram search: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#_minimum_document_count

Of course then this means you're basically sending empty data over the network, so there's pros and cons.

**Comment by adriaanvanrossum** [comment]
That would be great! Thanks James. Especially if we can till it with zeros. The example shows 1's, but I think 0's should work as well. I might have some time later today.

**Comment by adriaanvanrossum** [comment]
@Jivings is does not seem to work: https://github.com/elastic/elasticsearch/issues/4843 I tried, but no success.

**Comment by adriaanvanrossum** [comment]
I found a way with extended_bounds:

```js
histogram: {
  date_histogram: {
    field: 'timestamp',
    calendar_interval: params.interval,
    min_doc_count: 0,
    extended_bounds: {
      min: new Date(params.start),
      max: new Date(params.end)
    }
  }
}
```

https://seanmcgary.com/posts/elasticsearch-date-histogram-aggregation---filling-in-the-empty-buckets/
