### ISSUE TITLE
Clicking on the day in the chart does not work

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#478]
A customer did experience this, and it's also not working for me as well.

**Comment by alinacsava** [comment]
I didn't even know it was a thing. I clicked many times out of reflex, but took it as a given that it's not a feature. Needless to say I use Firefox.

**Comment by hellodeibu** [comment]
I had forgotten to test this section after some otherwise unrelated changes, sorry for the trouble! This has been fixed now, pending a deploy.

**Comment by adriaanvanrossum** [comment]
Deployed!
