### ISSUE TITLE
Add new header to dashboard

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#509]
Mobile:

<kbd><img width="420" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/103749183-79981280-5005-11eb-801c-7ce2cb110ad8.jpeg"></kbd>

Desktop:

<kbd><img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/103749186-7a30a900-5005-11eb-81c3-9e179721fe01.jpeg"></kbd>

cc @amritnagi

**Comment by jibsaramnim** [comment]
This is now merged into the beta branch and should become available once the new update goes public!
