### ISSUE TITLE
Fix disableing mailto onclick events in automated events script

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#511]
> I just wanted to let you know that your JavaScript for events caused an interesting behavior when we didn't want to have tracking for mailto links. Even though it generated onclick="undefined return false" - maybe you want to update your code that you wrap the whole block into a "if (collect)" so it looks like the attachment.
>
> Also thank you for the insights on your tech stack, really nice!

![image](https://user-images.githubusercontent.com/1079135/104102998-0bbb4780-52a0-11eb-8bbe-1666ab9bebc6.png)

See HS

**Comment by howdytom** [comment]
Thank you

**Comment by adriaanvanrossum** [comment]
No problem!
