### ISSUE TITLE
When searching, go to first page

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#520]
Instead of:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1079135/106455321-563d7780-648c-11eb-9e65-c7969d0c62cb.png">

I expect this:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1079135/106455361-65bcc080-648c-11eb-8d0c-146e357ce89d.png">

**Comment by hellodeibu** [comment]
This is working correctly in the new header branch, so I've added this issue to that PR! :)

**Comment by adriaanvanrossum** [comment]
Yeah, I fixed one of them in main:

https://github.com/simpleanalytics/main/blob/ec9d12895aa0933a7ec2b1382a24906a1e5212ed/dashboard/components/dashboard/Referrals.vue#L154

Not sure if that is applied to the other lists as well.
