### ISSUE TITLE
When searching the "compare filter" toggle is not updating the graph

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#526]
You would expect the chart to update based on the query as well. Can we add that?

![image](https://user-images.githubusercontent.com/1079135/107421577-6c95a400-6b1a-11eb-8404-4d67a6049bb4.png)

**Comment by jibsaramnim** [comment]
@adriaanvanrossum that's already happening actually, but I think there's an issue with the `Compare filtered` checkbox not working correctly (It seems like it's not actually hiding the unfiltered graph anymore). When I check on my end when entering a search query I do see the graph update -- could you do me a favor and check on your end to see if this matches with what you're seeing?

**Comment by adriaanvanrossum** [comment]
You are right, it's indeed an issue with compare filtered. When you hover over the chart you indeed see the numbers for the filtered stuff.

**Comment by jibsaramnim** [comment]
Thanks for confirming Adriaan! We've got a PR with fix pending review and deploy! :)
