### ISSUE TITLE
Adding new members with teams doesn't work (always)

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#527]
It seems like people can't always add others to their team. The email is send, they click the link, but it does not move add the new user.

**Comment by hellodeibu** [comment]
This one might have been related to #529, but some more testing is needed to make sure everything is working as it should. 

A current technical limitation prevents customers from inviting someone that already has a SA account, so a note for that might be added until correct support for this is added (which will likely be part of #521).

**Comment by adriaanvanrossum** [comment]
Let's close this in favor of our new system: https://github.com/simpleanalytics/roadmap/issues/535
