### ISSUE TITLE
Show all UTM codes in the dropdown

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#534]
- [x] Show all UTM codes in the dropdown (utm_source, utm_medium, utm_campaign, utm_content, utm_term)
- ~~Show amount of page views for each UTM code~~
- [x] Hide the dropdown if no page views are found for any UTM code

<kbd><img width="248" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/109121660-7e19b580-7782-11eb-9105-ac2fe7a0f936.png"></kbd>

**Comment by jibsaramnim** [comment]
> Show amount of page views for each UTM code

@adriaanvanrossum could you let me know what you have in mind for this one? As in, show it where, and how?

**Comment by adriaanvanrossum** [comment]
Something like this?

<kbd><img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/110408507-9e217100-80c0-11eb-8bff-20db3c2f66ac.png"></kbd>

**Comment by jibsaramnim** [comment]
> If the "page views/visitors" are much work, let's skip them. The most important thing is "Show all UTM codes in the dropdown".

Ah, perhaps it's better to create two separate issues yes. That way we can also spend a bit of extra time thinking about how to best display multiple numbers without causing confusion as to which number means what.

The "Referrals" option should then also show how many referrals are available, to match the behavior, right?

**Comment by jibsaramnim** [comment]
> Not sure if that's cluttering the UI too much. Let's try it out! Otherwise we can show that data on hover with a tooltip or something.

Right, or we can only show those numbers in the menu, but not display it in the section title.

**Comment by jibsaramnim** [comment]
This is now merged into the beta branch and should become available once the new update goes public!
