### ISSUE TITLE
Referral thumbnails are not showing up anymore

### ISSUE THREAD

**Issue by jibsaramnim** [simpleanalytics/roadmap#570]
Referral thumbnails that are supposed to show up when filtering on a referrer no longer show up. 

As reported by Amrit in the insiders group.

**Comment by adriaanvanrossum** [comment]
Should this be fixed in ES, right?

**Comment by jibsaramnim** [comment]
@adriaanvanrossum it seems like it, as Amrit mentioned in the insiders group it's working as expected on beta, which is still using the "old" ES server. So that seems to suggest the problem is somehow related to what `data2` does or has that is different from `data`.

**Comment by adriaanvanrossum** [comment]
Cool, will check that one then. Thanks!

**Comment by jibsaramnim** [comment]
@adriaanvanrossum I think this one is fixed, right? I'll go ahead and close the issue, please feel free to reopen if I made a mistake! :)
