### ISSUE TITLE
Add tooltip to visitors online now

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#571]
> @Jivings:
> ![image](https://user-images.githubusercontent.com/1079135/116178488-3eeaef00-a748-11eb-91bd-7f7dc9bd1a27.png)
> can we have a tooltip here please 😊
> We have 200+ pages that start with `/how-to-unsubscribe-` 🤪
> Adding a `title` attribute to the line with the full path would work for me

Let's add this!

**Comment by jibsaramnim** [comment]
Implemented, pending deploy! :)
