### ISSUE TITLE
Number on iOS widget

### ISSUE THREAD

**Issue by RubenVanEldik** [simpleanalytics/roadmap#574]
When the page count goes above a 1000 for a given day the number does not fit anymore. I think this could be fixed by decreasing the font size or using the rounded value (e.g. 1.3k).

![D4C54127-0EEA-4CD6-BFD1-FB5FF5265AB9](https://user-images.githubusercontent.com/25854734/116565461-2f190980-a906-11eb-9098-750340a12ce8.jpeg)

**Comment by onurgenes** [comment]
We can continue like this or we can remove the `Yesterday's Analytics` text.

![Today Widget](https://user-images.githubusercontent.com/9106330/118642041-8d3d5c00-b7e3-11eb-82e7-7ca9471cff49.png)

![Yesterday Widget](https://user-images.githubusercontent.com/9106330/118642064-94646a00-b7e3-11eb-8659-36fd8e8032f0.png)

**Comment by adriaanvanrossum** [comment]
Maybe it's better to have:

```
Today
337
simpleanalytics.com
```

Or

```
Yesterday
1032k
simpleanalytics.com
```

**Comment by onurgenes** [comment]
I think it is better now.

<img src="https://user-images.githubusercontent.com/9106330/118642774-692e4a80-b7e4-11eb-914f-fca6957a7a87.png" width="300"> | <img src="https://user-images.githubusercontent.com/9106330/118642783-6e8b9500-b7e4-11eb-973b-4ba31ecac563.png" width="300">

**Comment by adriaanvanrossum** [comment]
Can it handle 55555 visits as a number as well?

**Comment by onurgenes** [comment]
Of course. It can handle everything right now.

**Comment by adriaanvanrossum** [comment]
@RubenVanEldik This is now live in the App Store!
