### ISSUE TITLE
Make sure the whole row (including % is clickable)

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#577]
In our dashboard it's not always click where to click. Let's make it clickable everywhere and filter that way. A customers told us that they though the filters didn't work for devices, browsers, and countries.

|https://simpleanalytics.com/simpleanalytics.com |
|--- |
|<img width="545" alt="image" src="https://user-images.githubusercontent.com/1079135/117638790-cce9bf80-b1b5-11eb-9e9c-3e37e253bbc6.png">|

**Comment by jibsaramnim** [comment]
This is implemented and will be available in the next update! :)
