### ISSUE TITLE
Unclosed tag on roadmap page ?

### ISSUE THREAD

**Issue by Carreau** [simpleanalytics/roadmap#580]
https://simpleanalytics.com/roadmap page there is a layout issue with the chat button which is half hidden on lower left.
See screenshot

<img width="912" alt="Screen Shot 2021-05-15 at 10 20 16" src="https://user-images.githubusercontent.com/335567/118372576-3af00700-b567-11eb-87ad-af7e7d470057.png">

And clicking the chat button opens `https://github.com/simpleanalytics/roadmap/issues/569` in a new tab as well as opening the chat.

Probably an unclosed tag ?

(Sidenote, I'd love to be able to see the login-only pages and how to add domains/website without starting a trial).

And already told you in the chat, but in https://docs.simpleanalytics.com/overwrite-domain-name : then -> than

```diff
- Or you want to use a different domain then people see in their browser address bar
+ Or you want to use a different domain than people see in their browser address bar
```

**Comment by adriaanvanrossum** [comment]
Thanks!

Fixed the typo here: https://github.com/simpleanalytics/docs/commit/fd34dddd9fd4e0b4054e0d4b8c041a7c54fbe716

And the roadmap is now fixed as well.
