### ISSUE TITLE
Add date picker to chart overview

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#581]
Would love to add a date picker to our iOS app so people can get their data for a certain period.

- [ ] Show data range in UI
- [ ] Add edit button
- [ ] Make edit button open up native date picker modal (see screenshot 2)
- [ ] Adjust API calls to check for dates
- [ ] Make sure to send current time zone with API call (or use time zone of website)

<img src="https://user-images.githubusercontent.com/1079135/118489290-41d96e00-b74f-11eb-8a55-baed4dfae715.png" width="500px">

<img src="https://user-images.githubusercontent.com/1079135/118486969-cf678e80-b74c-11eb-92f9-455948d0af43.png" width="320px"> 

- [iOS 14 變成月曆的 date picker](https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E5%95%8F%E9%A1%8C%E8%A7%A3%E7%AD%94%E9%9B%86/ios-14-%E8%AE%8A%E6%88%90%E6%9C%88%E6%9B%86%E7%9A%84-date-picker-66f6d9ffa431)
- https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/

**Comment by onurgenes** [comment]
<img src="https://user-images.githubusercontent.com/9106330/119228627-82086a00-bb1c-11eb-8aa0-85232877aff6.jpg" width="300">

Because of the limitations of the SwiftUI's current state, I have decided to use 2 date pickers. I wish we can fix this on the later versions of SwiftUI.
