### ISSUE TITLE
Add important numbers above chart

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#582]
It would make sense add totals of page views, visitors, and time on page to the chart.

<img src="https://user-images.githubusercontent.com/1079135/118488636-86183e80-b74e-11eb-8c71-f77f1af47150.png" width="585px">

**Comment by onurgenes** [comment]
<img src="https://user-images.githubusercontent.com/9106330/119230188-debb5300-bb23-11eb-9d99-e78822d9af29.png" width="300">

Made it like this and that was a great idea!
