### ISSUE TITLE
Little dashboard issues

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#598]
A list of little things that need some polishing

- [x] Navigation bar seems to be white now (https://github.com/simpleanalytics/roadmap/issues/600)
- [x] Icon does not show while it is in the database ([icon URL](https://simpleanalytics.com/favicons/blog.simpleanalytics.com.png))
  <kbd><img width="545" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121520497-8f32bd80-ca25-11eb-9d54-aab79d9a330c.png"></kbd>
  ```js
  {"favicon": {"url": "https://simpleanalytics.com/favicons/blog.simpleanalytics.com.png", ...}
  ```
- [x] Dropdown menu is overflown when domain is very short. We might align that dropdown left instead of right?
  <kbd><img width="511" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121520781-e8025600-ca25-11eb-8a0e-8399999d98e4.png"></kbd>
- [x] Give a bit more space above and below the website icon on mobile
  <kbd><img width="376" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121521288-7971c800-ca26-11eb-925e-911961eeeba0.png"></kbd>
- [x] Give a bit more space on the right and below the account menu items on mobile
  <kbd><img width="375" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121521436-a45c1c00-ca26-11eb-889c-2ca32acc101e.png"></kbd>
- [x] Show first name in new header (like it's with the other navigation bar):
  <kbd><img width="539" alt="Screenshot" src="https://user-images.githubusercontent.com/1079135/121526328-d9b73880-ca2b-11eb-8919-435c94af9335.png"></kbd>

**Comment by jibsaramnim** [comment]
- [x] Now Online counter isn't updating correctly after switching to another website (as reported by Amrit)
