### ISSUE TITLE
Matomo/Other/None choices in "What tool are you considering Replacing" link to Google Analytics specific article/test

### ISSUE THREAD

**Issue by jibsaramnim** [simpleanalytics/roadmap#614]
As reported by a customer. 

The [article linked to](https://simpleanalytics.com/the-easy-answer) covers the subject of analytics and privacy in more general terms, but its final sentence and all `Take the test` buttons do point to [a comparison with Google Analytics and Simple Analytics](https://simpleanalytics.com/compare-google-with-simple-analytics), not Matomo. The same applies if you had selected `Other` or `None`.

![image](https://user-images.githubusercontent.com/18850/128625529-bcf374e0-00ce-4d74-a1aa-0776c7a0bb04.png)

**Comment by adriaanvanrossum** [comment]
Yes, we will redo the home page at some point. So will close this for now.
