### ISSUE TITLE
Danish character don’t work in iOS app

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#636]
> Im using the app on my iPhone X and it crashes when I want to access the data from a domain in the list containing danish letters.... 

Eg `grøn.dk`

**Comment by onurgenes** [comment]
May I have a sample credentials with Danish characters? Or credentials of the actual user?

**Comment by adriaanvanrossum** [comment]
I don't have those, but you could add `grøntestwebsite.dk` and see if it shows an error?

**Comment by onurgenes** [comment]
I have sent the updated files. You can build and test if needed @adriaanvanrossum

**Comment by adriaanvanrossum** [comment]
Beta is in review now.

**Comment by adriaanvanrossum** [comment]
Seems to work great!

![image](https://user-images.githubusercontent.com/1079135/143213902-a49873e3-104c-4534-aa5d-7b2caa6fe1e9.png)

**Comment by adriaanvanrossum** [comment]
Update pushed to the App Store.
