### ISSUE TITLE
Option to disable/remove campaign level tracking

### ISSUE THREAD

**Issue by romainmenke** [simpleanalytics/roadmap#676]
We would prefer it if campaign related url params added by 3rd parties were not send to Simple Analytics.
Is this something that can be configured in the client side script?

**Comment by adriaanvanrossum** [comment]
Except for UTM codes, we don't collect any query params, only if you specifically specify them. Could you explain your use case a bit more?

If that data is inside a path, you can overwrite it: https://docs.simpleanalytics.com/overwrite-path

If you want to ignore certain metrics: https://docs.simpleanalytics.com/ignore-metrics

If you want to only collect strict UTMs: https://docs.simpleanalytics.com/strict-utms

**Comment by romainmenke** [comment]
> If you want to ignore certain metrics: https://docs.simpleanalytics.com/ignore-metrics

We missed this one, thank you for pointing it out!

**Comment by adriaanvanrossum** [comment]
Awesome, happy to help!
