### ISSUE TITLE
Show top pages per referral

### ISSUE THREAD

**Issue by adriaanvanrossum** [simpleanalytics/roadmap#9]
> Basically, it'd be helpful to see which referrals lead to which pages. That way I can see if searches are more likely to land on the home page or the pricing page, etc.

Thanks to @dinkydani21 and @lseelenbinder:

> Referrals by page; Basically, it'd be helpful to see which referrals lead to which pages. That way I can see if searches are more likely to land on the home page or the pricing page, etc

**Comment by adriaanvanrossum** [comment]
This is implemented! Let me know if this works for you @lseelenbinder.

**Comment by lseelenbinder** [comment]
Thanks @adriaanvanrossum—looking great!
